import { MigrationInterface, QueryRunner } from 'typeorm';

export class TryToAddAutoGeneratedUUID1745443743731
  implements MigrationInterface
{
  name = 'TryToAddAutoGeneratedUUID1745443743731';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "event_participants" DROP CONSTRAINT "FK_event_participants_participant"`,
    );
    await queryRunner.query(
      `ALTER TABLE "event_participants" DROP CONSTRAINT "FK_event_participants_event"`,
    );
    await queryRunner.query(
      `ALTER TABLE "event_participants" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "event_participants" ALTER COLUMN "id" DROP DEFAULT`,
    );
    await queryRunner.query(
      `ALTER TABLE "event_participants" ADD CONSTRAINT "FK_event_participants_event" FOREIGN KEY ("evento") REFERENCES "event"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "event_participants" ADD CONSTRAINT "FK_event_participants_participant" FOREIGN KEY ("participante") REFERENCES "participant_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
  }
}
